// Service worker: hra beží po prvom otvorení aj bez internetu (verzia 37c5d7e91b).
const CACHE = 'mk12-37c5d7e91b';
const FILES = ["./", "index.html", "manifest.webmanifest", "assets/manifest.js", "assets/matusko/block.png", "assets/matusko/dizzy.png", "assets/matusko/fall.png", "assets/matusko/flip.png", "assets/matusko/hit.png", "assets/matusko/idle.png", "assets/matusko/jump.png", "assets/matusko/kiai.png", "assets/matusko/kick.png", "assets/matusko/punch.png", "assets/matusko/special.png", "assets/matusko/walk.png", "assets/matusko/win.png", "assets/music/fight.mp3", "assets/music/result.mp3", "assets/music/title.mp3", "assets/rocky/lick.png", "assets/rocky/run.png", "assets/sfx/baby.mp3", "assets/sfx/bark.mp3", "assets/sfx/block.mp3", "assets/sfx/crack.mp3", "assets/sfx/fall.mp3", "assets/sfx/folklority.mp3", "assets/sfx/heligonka.mp3", "assets/sfx/husle.mp3", "assets/sfx/kiai.mp3", "assets/sfx/kick.mp3", "assets/sfx/lick.mp3", "assets/sfx/notes.mp3", "assets/sfx/punch.mp3", "assets/sfx/whoosh.mp3", "assets/simon/block.png", "assets/simon/dance.png", "assets/simon/dizzy.png", "assets/simon/fall.png", "assets/simon/flip.png", "assets/simon/hit.png", "assets/simon/idle.png", "assets/simon/jump.png", "assets/simon/kiai.png", "assets/simon/kick.png", "assets/simon/kroj.png", "assets/simon/punch.png", "assets/simon/special.png", "assets/simon/walk.png", "assets/simon/win.png", "assets/stages/dojo.png", "assets/stages/more.png", "assets/stages/potok.png", "assets/stages/tabor.png", "assets/ui/cake_matusko.png", "assets/ui/cake_simon.png", "assets/ui/emblem.png", "assets/ui/icon192.png", "assets/ui/icon512.png", "assets/ui/portrait_matusko.png", "assets/ui/portrait_simon.png", "assets/voice/babality.mp3", "assets/voice/birthday.mp3", "assets/voice/creeperality.mp3", "assets/voice/draw.mp3", "assets/voice/fight.mp3", "assets/voice/finish.mp3", "assets/voice/flawless.mp3", "assets/voice/folklority.mp3", "assets/voice/friendship.mp3", "assets/voice/matusko_wins.mp3", "assets/voice/rockyality.mp3", "assets/voice/round1.mp3", "assets/voice/round2.mp3", "assets/voice/round3.mp3", "assets/voice/simon_wins.mp3", "assets/voice/ssj_matusko.mp3", "assets/voice/ssj_simon.mp3", "assets/voice/title.mp3", "game.js"];
self.addEventListener('install', e => e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting())));
self.addEventListener('activate', e => e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())));
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET' || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(r => r || fetch(e.request)));
});
